import { Task } from './lib/types'
import { generateId } from './lib/utils'

export const tasks: Task[] = [
  {
    id: generateId(),
    title: 'Write project proposal',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Fix login page bug',
    status: 'not_started',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Design homepage layout',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Update API documentation',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Refactor user authentication',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Optimize database queries',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Review PR #345',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Implement dark mode',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Schedule team meeting',
    status: 'completed',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Prepare monthly report',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Fix CSS styling issue',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Set up CI/CD pipeline',
    status: 'not_started',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Test new feature deployment',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Debug performance issues',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Create marketing email template',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Write unit tests for authentication',
    status: 'not_started',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Optimize frontend rendering',
    status: 'completed',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Update dependency versions',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Research competitor products',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Draft feature roadmap',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Create onboarding guide',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Prepare client presentation',
    status: 'completed',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Configure analytics tracking',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Conduct code review session',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Fix mobile responsiveness issues',
    status: 'not_started',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Improve error handling',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Set up monitoring alerts',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Design new logo',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Analyze customer feedback',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Write blog post on best practices',
    status: 'not_started',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Document REST API endpoints',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Refactor checkout flow',
    status: 'not_started',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Optimize image loading',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Update security policies',
    status: 'not_started',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Develop user profile page',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Fix broken links in footer',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Set up automated email responses',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Improve site accessibility',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Create A/B test experiment',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Conduct usability testing',
    status: 'not_started',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Write post-mortem for outage',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Fix pagination issues',
    status: 'not_started',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Build dashboard charts',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Write test cases for search functionality',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Improve onboarding flow',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Optimize SQL queries',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Deploy new microservice',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Fix UI inconsistencies',
    status: 'not_started',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Update payment gateway integration',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Investigate slow API response times',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Prepare for product launch',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Write user documentation',
    status: 'completed',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Update README file',
    status: 'not_started',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Fix session expiration bug',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Develop chat feature',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Research AI integration',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Improve website SEO',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Analyze error logs',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Redesign settings page',
    status: 'completed',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Enhance form validation',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Update email templates',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Set up feature flags',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Fix typos in UI copy',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Refactor old legacy code',
    status: 'not_started',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Prepare training slides',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Create FAQ section',
    status: 'completed',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Fix timezone issues',
    status: 'not_started',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Add 2FA authentication',
    status: 'not_started',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Implement search autocomplete',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Improve cache strategy',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Update terms of service',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Research new frontend framework',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Enhance error messages',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Fix memory leak issue',
    status: 'not_started',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Develop new admin panel',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Review customer support tickets',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Run load tests',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Write Cypress tests',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Create interactive tutorial',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Fix API CORS issues',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Enhance keyboard navigation',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Update user avatars',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Test backup recovery',
    status: 'not_started',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Update mobile app version',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Monitor server logs',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Fix infinite scroll bug',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Improve site speed',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Write migration script',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Develop feature toggles',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Refactor modal components',
    status: 'in_progress',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Conduct A11y audit',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Test WebSocket connections',
    status: 'not_started',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Optimize database indexing',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Fix missing translations',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Investigate 500 errors',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Update dark mode styling',
    status: 'completed',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Review legal compliance',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Write changelog updates',
    status: 'completed',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Deploy security patches',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Refactor Redux state',
    status: 'completed',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Fix sidebar navigation',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Improve touch gestures',
    status: 'in_progress',
    priority: 'medium',
  },
  {
    id: generateId(),
    title: 'Update typography guidelines',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Test push notifications',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Fix dropdown positioning',
    status: 'not_started',
    priority: 'low',
  },
  {
    id: generateId(),
    title: 'Develop new analytics dashboard',
    status: 'completed',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Reduce bundle size',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Refactor date parsing functions',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Improve modal animations',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: generateId(),
    title: 'Run penetration tests',
    status: 'not_started',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Implement JWT authentication',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: generateId(),
    title: 'Improve logging strategy',
    status: 'in_progress',
    priority: 'none',
  },
  {
    id: generateId(),
    title: 'Optimize Redis caching',
    status: 'not_started',
    priority: 'high',
  },
]
